#release configuration
#Fri Jul 17 16:44:50 EDT 2026
projectVersionPolicyId=default
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
project.scm.org.janelia.saalfeldlab\:n5-spark.tag=HEAD
pinExternals=false
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
project.scm.org.janelia.saalfeldlab\:n5-spark.url=https\://github.com/saalfeldlab/n5-spark
exec.activateProfiles=deploy-to-scijava
pushChanges=false
project.scm.org.janelia.saalfeldlab\:n5-spark.developerConnection=scm\:git\:git@github.com\:saalfeldlab/n5-spark
project.rel.org.janelia.saalfeldlab\:n5-spark=4.1.0
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
releaseStrategyId=default
project.dev.org.janelia.saalfeldlab\:n5-spark=4.1.1-SNAPSHOT
completedPhase=end-release
scm.url=scm\:git\:https\://github.com/saalfeldlab/n5-spark
scm.developmentCommitComment=@{prefix} prepare for next development iteration
exec.additionalArguments=-Dgpg.skip\=true 
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.tag=n5-spark-4.1.0
project.scm.org.janelia.saalfeldlab\:n5-spark.connection=scm\:git\:git\://github.com/saalfeldlab/n5-spark
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
exec.pomFileName=pom.xml
